#!/bin/sh
APPDIR=`dirname $0`;
LIBS=$GWT_HOME/gwt-user.jar
LIBS=$LIBS:$GWT_HOME/gwt-dev-linux.jar
LIBS=$LIBS:$APPDIR/lib/gwt-dnd-2.5.6.jar
LIBS=$LIBS:$APPDIR/lib/gwt-incubator.jar
LIBS=$LIBS:$APPDIR/lib/gwt-beans-binding-0.2.1.jar
LIBS=$LIBS:$APPDIR/lib/gwtx-1.5-20081912.jar
LIBS=$LIBS:$APPDIR/lib/derby.jar
LIBS=$LIBS:$APPDIR/lib/toplink-essentials.jar
LIBS=$LIBS:$APPDIR/lib/toplink-essentials-agent.jar
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/build/classes:$LIBS" com.google.gwt.dev.GWTShell -out "$APPDIR/build/www" "$@" org.gwt.mosaic.showcase.Showcase/Showcase.html;
